### ISSUE TITLE
Make swiping back and forth bad for score

### ISSUE THREAD

**Issue by Jared-Sprague** [redhataccess/engage-game#2]
people mindlessly swiping back and forth to catch all blocks should get a bad score for not trying.

possible solution:  more vunls

**Comment by mwcz** [comment]
@Jared-Sprague do you think swiping is still too effective?

**Comment by mwcz** [comment]
@Jared-Sprague  Should we close this?

**Comment by Jared-Sprague** [comment]
yep closed
